/**
 * @author Themba Malungani <themba.clarence@gmail.com>
 * @description Used to encapsulate strings
 * @date 2019-10-21
 */
public class Strings {
  public static final String STANDARD_PRICE_BOOK      = 'Standard Price Book';
  public static final String OP_STAGE_NEW_INTEREST    = 'New Interest';
  public static final String SEGMENT_PENDING_SYNC     = 'New Opportunity Pending Synchronisation';
  public static final String CURRENCY_USD             = 'USD';
  public static final String REQUEST_A_CALL           = 'Request a call';
  public static final String REQUESTED_A_CALL         = 'Requested a call';
  public static final String NO_PRODUCT_PASSED        = 'No product Id was passed';
}
