public class Strings {
  public static final String STANDARD_PRICE_BOOK      = 'Standard Price Book';
  public static final String OP_STANE_NEW_INTEREST    = 'New Interest';
  public static final String SEGMENT_PENDING_SYNC     = 'New Opportunity Pending Synchronisation';
  public static final String CURRENCY_USD             = 'USD';
  public static final String REQUEST_A_CALL           = 'Request a call';
}
